### ISSUE TITLE
Unity playersettings need to change .net2.0?

### ISSUE THREAD

**Issue by zhaoqingqing** [Meragon/Unity-WinForms#1]
this lib need to change unity playersettings **api compatibility level**

 form **.Net2.0 Subset** to **.Net2.0**？if i want to export windows standalone exe
![image](https://cloud.githubusercontent.com/assets/3056814/17076436/2267e442-50e4-11e6-9e0f-bfb84fff557a.png)

**Comment by Meragon** [comment]
It's support both of the API, because it's using only Unity code and there is no dll's or something.
So you can use whatever you want.

**Comment by zhaoqingqing** [comment]
ok，thank you . 

before i copy System.Windows.Forms.dll to unity/Assets/Plugins ，the form.dll need change to .Net 2.0 ,the change is too big,  my game run on webplayer platform and windows platform ，so i give up it.

you project is source code，very good

**Comment by Meragon** [comment]
You don't need to use System.Windows.Forms.dll. I mean, I'm not supporting official dll from Microsoft (same as System.Drawing.dll), just making my own implementation of them.

**Comment by zhaoqingqing** [comment]
ok . i know you write own implementation  for it .
you did a good job . thank you
