### ISSUE TITLE
suggest  release dll  or visual studio project?

### ISSUE THREAD

**Issue by zhaoqingqing** [Meragon/Unity-WinForms#2]
hi，i want to release a dll ,and create visual studio project，but is need some time ,
so if you can release a dll，or create visual studio projecto?
that will very nice for user
![image](https://cloud.githubusercontent.com/assets/3056814/17077310/2885c866-50fe-11e6-88b7-b83655eade9f.png)

**Comment by Meragon** [comment]
I made example project for you [https://drive.google.com/drive/u/0/folders/0B5cwNJP-RMf4Sk9YQzMzUVdtV2c](google disk)

**Comment by zhaoqingqing** [comment]
oh , thank you example ,is simple to use .it work well in unity 5.x,(i both work in unity 5.3.4f1 and unity 4.x).
and i want you can add this example to you git project release to help more people introduction.
best wish to you .

**Comment by Meragon** [comment]
Just added [here](https://github.com/Meragon/Unity-WinForms/releases). Still, there is a lot of things that should be done, and that's why I was not making any releases.
But thank you anyway.

**Comment by zhaoqingqing** [comment]
i read this project's source code ,well done.
