### ISSUE TITLE
It is easy to use when you are support .unitypackage.

### ISSUE THREAD

**Issue by netpyoung** [Meragon/Unity-WinForms#20]
using github's release feature or modify readme, support .unitypackage will be easy to use for users.

**Comment by Meragon** [comment]
If only for those, who don't have a git installed, yeah. Anyway I'll do it tomorrow, cause I do not plan to update project in the near future.

**Comment by Meragon** [comment]
Done.
https://github.com/Meragon/Unity-WinForms/releases/tag/7
