### ISSUE TITLE
Sorry，Unity-WinForms-6 up to now do not work between Unity5.6-Unity2018.

### ISSUE THREAD

**Issue by superowner** [Meragon/Unity-WinForms#23]
uwfAppOwner is null

**Comment by Meragon** [comment]
Just checked with 2017.3.0f3. Everything is fine. 
Provide me with more info or just upload your project, I'll take a look.

**Comment by superowner** [comment]
void Start () {
        
        var form = new Form();
        form.Show();
    }

error:
NullReferenceException: Object reference not set to an instance of an object
System.Windows.Forms.Form._MakeButtonClose () (at Assets/System/Windows/Forms/Form.cs:347)
System.Windows.Forms.Form.set_ControlBox (Boolean value) (at Assets/System/Windows/Forms/Form.cs:86)
System.Windows.Forms.Form..ctor () (at Assets/System/Windows/Forms/Form.cs:40)
(wrapper remoting-invoke-with-check) System.Windows.Forms.Form:.ctor ()
NewBehaviourScript.Start () (at Assets/NewBehaviourScript.cs:11)

**Comment by Meragon** [comment]
What last commit are you using? There is not such a line in Form.cs at 347. I checked both, released and current version.

**Comment by Meragon** [comment]
I know where it is. I just don't know which version are you using to recreate an error.
If you didn't change anything in code, then probably it means that UnityWinForms scripts is starting after you creating new Form.
UnityWinForms must create a new controller and set it as default to use in any controls.
```
public sealed class UnityWinForms : UE.MonoBehaviour
{
   private void Awake()
   {
      ...
      controller = new Application();
      controller.Resources = GdiImages;
      controller.UpdatePaintClipRect();

      Control.uwfDefaultController = controller;
      ...
```

**Comment by superowner** [comment]
Oh, I get,Thank you!

**Comment by Meragon** [comment]
You welcome.

**Comment by HUSTlwr** [comment]
hey!
On 2018.3.11f1- x64 win10
I had the same problem as @superowner. 
`if (uwfAppOwner.Resources != null && uwfAppOwner.Resources.Close != null)` was wrong.
I try to use your method to solve this problem. It works, but a new problem has emerged.
This is my Awake():

`private void Awake()
{

        AppGdiImages GdiImages = new AppGdiImages();
        System.Windows.Forms.Application controller = new System.Windows.Forms.Application();
        controller.Resources = GdiImages;
        controller.UpdatePaintClipRect();
        Control.uwfDefaultController = controller;

 }`

error:
NullReferenceException: Object reference not set to an instance of an object
System.Windows.Forms.Cursor.set_Current (System.Windows.Forms.Cursor value) (at Assets/WinForm/System/Windows/Forms/Cursor.cs:38)
System.Windows.Forms.Application..ctor () (at Assets/WinForm/System/Windows/Forms/Application.cs:49)
NewForm.Awake () (at Assets/Scripts/NewForm.cs:16)

"NewForm.cs:16" in my scripts is :
`System.Windows.Forms.Application controller = new System.Windows.Forms.Application();`

**Comment by Meragon** [comment]
Hey @HUSTlwr 
Sounds like you are using your own controller and not setting images. You better check UnityWinForms.cs file. Basically there is no need to create your own controller, because it is already exists. Just add it to some GameObject,
Also there is example version in [https://github.com/Meragon/Unity-WinForms/releases/tag/10](releases).

**Comment by HUSTlwr** [comment]
thanks, I get it.
