### ISSUE TITLE
Code Editor Example

### ISSUE THREAD

**Issue by diwot** [Meragon/Unity-WinForms#26]
Hi, is the Code Editor you present as an example on the description page available in a github project? If yes, could you provide the link, I was not able to find it. The same for the material design example, is that also available somewhere? Thanks.
https://camo.githubusercontent.com/c4c061bdf76cee66895ddd5f8daf586f52435417/68747470733a2f2f692e696d6775722e636f6d2f594a33593542442e706e67

**Comment by Meragon** [comment]
Hey.
The code editor is part of my job project, it's sources probably not gonna be released. It's possible when the whole project will be open sourced (and we still think about it). 
As for material design stuff. The code is kinda messy, I was just testing out possibilities of WinForms. If you need it, I can upload it somewhere.

**Comment by PalashBansal96** [comment]
Hey, did you finally upload the projects somewhere? It would be really great to learn from them.

**Comment by Meragon** [comment]
Hey, no, I didn't. Was kinda forgot about that question. I'm gonna try to do that on this weekends.

**Comment by Meragon** [comment]
uploaded here [https://github.com/Meragon/MaterialUnityForms](MaterialUnityForms)
