### ISSUE TITLE
How to use my own imported .ttf font file?

### ISSUE THREAD

**Issue by HUSTlwr** [Meragon/Unity-WinForms#28]
I added the .ttf font file format to the Asset folder. The name of .ttf font file is "times new roman.ttf". And then, I added font to the script UnityWinForms. 
![23e8db1f7e62c1a5568f39d9b6df930](https://user-images.githubusercontent.com/50614735/71864776-be137880-313b-11ea-8d5b-701652112a98.png)

I used the font that I imported in a new script.
`Form form = new Form();`
`form.Font = new System.Drawing.Font("times new roman", 11);`

But there was a error about "Font not found".
![2a157de0388acaf85ad4d8cb81263bf](https://user-images.githubusercontent.com/50614735/71864901-28c4b400-313c-11ea-9aef-37ea335cfdab.png)

I wondered if there was something wrong with the format of my imported font file, or something else.

thanks!

**Comment by Meragon** [comment]
The file name may differ from the font name. Look at the font name in the inspector by first clicking on it.

**Comment by HUSTlwr** [comment]
thanks！
