### ISSUE TITLE
Is this cross platform?

### ISSUE THREAD

**Issue by TheBricktop** [Meragon/Unity-WinForms#32]
Hello im very interested in porting AccordNet to unity and use it in mobile devices, but it depends heavily on system.drawing, is Your version cross platform?

**Comment by Meragon** [comment]
Hey.
Yes it is, but the drawing library is not fully implemented (like Regions, TextureBrushes, Pen styles).

**Comment by TheBricktop** [comment]
Holy canolli, ive only needed some filters and color for now.
Im so happy.

**Comment by Meragon** [comment]
Best luck. And I also want to say that it will be probably hard time scaling UI on mobile devices.
The things you can do is: 
- set app resolution;
- use Application.ScaleX and Application.ScaleY properties;
- write some controller that can rescale all forms/controls dynamically;

**Comment by TheBricktop** [comment]
I dont know if ill use the ui, probably just some classes from system.drawing
