### ISSUE TITLE
Textbox focus color and text color are the same

### ISSUE THREAD

**Issue by damonftl** [Meragon/Unity-WinForms#33]
I'm having quite a time trying to make it so that the text color and focus background color for a text box are different. When you click on a text box to enter some text, the background changes to the same color as the text, very dark gray. There appears to be no way to change just the focus color. 

When you change the ForeColor for your Textbox and then click on the text box, the focus color is different, but the text is now also that color, so there is no way to see what you are typing. The same thing actually happens with NumericUpDowns too. It happens in the Examples as well. I'll attach an image showing it with the NumericUpDown in the examples. Can anything be done about this?

![numericupdownexample](https://user-images.githubusercontent.com/61205651/87082450-0ef24f80-c1f9-11ea-986e-4c981c943af0.jpg)

**Comment by Meragon** [comment]
Yeah, it's a new Unity 'feature', I even sent them the report, on which they reply that it works as intended now.
Anyway, I fixed it quite a while ago, give me a moment to upload fix.
