### ISSUE TITLE
Buttons do not respond to events

### ISSUE THREAD

**Issue by sui0312feng** [Meragon/Unity-WinForms#34]
MessageBox.Show("zsq","zsq");
        
        Button button1 = new Button();
        button1.Location = new Point(108, 101);
        button1.Name = "button1";
        button1.Size = new Size(75, 23);
        button1.TabIndex = 0;
        button1.Text = "button1";
        button1.Click += (sender, args) =>
        {
            Debug.Log("test2");
           
        };

        Form form = new Form();
        form.Text = "zsq";
        form.MinimumSize = new Size(600, 400);
        form.Controls.Add(button1);
        
        form.Show();

![image](https://user-images.githubusercontent.com/9710113/87652179-79216c00-c786-11ea-9b70-b07a207cc05d.png)

**Comment by sui0312feng** [comment]
button can not execute event. Unable to output log information

**Comment by sui0312feng** [comment]
form can not be closed

**Comment by Meragon** [comment]
[MessageBox](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.messagebox?view=netcore-3.1)is a [modal](https://en.wikipedia.org/wiki/Modal_window) form.

**Comment by sui0312feng** [comment]
click "Ok" should close this form! but it is not

**Comment by Meragon** [comment]
Can you upload example project?

**Comment by sui0312feng** [comment]
i sent email to you ,the project  is in the attachment

**Comment by sui0312feng** [comment]
dragon33@bk.ru   ,do you receive the email?

**Comment by Meragon** [comment]
Yeah, I did. 
It looks like inheriting from the UnitoWinForms class prevents the underlying code from executing. If you inherit the 'Shoot' class from MonoBehavour, then everything will work. Seems strange thing.

**Comment by sui0312feng** [comment]
ok,  i will try it ,thanks

**Comment by sui0312feng** [comment]
i  Put "Form form"outside of "start" and it works.
