### ISSUE TITLE
Guide for usage?

### ISSUE THREAD

**Issue by mariugul** [Meragon/Unity-WinForms#36]
Would it be possible to make a more detailed description of how you would actually use this in a project? It seems like a really good implementation of WinForms in Unity, but it's a bit hard to get started using it.

**Comment by Meragon** [comment]
A you asking about how to set this up? Or in general how to work with Windows Forms? Or maybe what can you achieve with this code? 
There is an example form that can help you to understand what is going on. Also I have a second example project [here](https://github.com/Meragon/MaterialUnityForms)

**Comment by mariugul** [comment]
I'm aware of how to work with WinForms, at least on a basic level so I'm asking more in terms of how you would go about incorporating this into a Unity project and start drawing up buttons and such. I've looked at the example, but I still find it quite hard to know where to start on setting up a script for say, a WinForm toolbar for example. I guess I have a few questions:

-  Is the only option to draw up buttons etc. in code, and specifying in code their position?

- If I were to add just one WinForm object (toolbar, button etc), what scripts and code does one need?

**Comment by Meragon** [comment]
> Is the only option to draw up buttons etc. in code, and specifying in code their position?
Yes, there is no designer, like in the Visual Studio. Everything should be written by hand.
> If I were to add just one WinForm object (toolbar, button etc), what scripts and code does one need?
You can't. Same as in original the WinForms. You can add a form and then do some 'tricks' (such as overriding paint code in form).
> Just a thought from my side that it would be useful with a small written guide on setting up a basic small couple of WinForm objects so it's easier to get started without going through a huge example where so much is happening it's easy to get lost in the code :)
I mean, yes, there is some undocumented changes, but practically it's all the same thing. 
Like code in here https://github.com/Meragon/Unity-WinForms/blob/master/Examples/Panels/PanelPictureBox.cs
`var pictureBox = this.Create<PictureBox>();
this.Create<Label>("Border style:", false, 8, 64);
var comboBorder = this.Create<ComboBox>();`
It's an extensions methods, you don't have to use them, because I don't. In my project I have other ones. But basically it says something like:
`var pictureBox = new PictureBox()
pictireBox.Location = new Point(32, 8); // Depends on other controls in parent form.
this.Controls.Add(pictureBox);
// And so on.`

**Comment by mariugul** [comment]
What you are talking about with overriding paint code and such, does that mean I would be able to have the WinForm with a toolbar for example, and then make the rest of the form "invisible"? What I essentially want to accomplish is add the windows GUI with a toolbar with "File, Export" etc. that can also open and save files. Would this be a feasible thing with this WinForm port with my project that looks like this? 

![image](https://user-images.githubusercontent.com/32439744/88852993-5617a300-d1ef-11ea-8302-00d6e1966fd3.png)

Or would you rather recommend just use native Unity GUI and create my own to simulate the Windows native GUI?

**Comment by Meragon** [comment]
Yes, it's possible. Here is the example:
```csharp
public class TestForm : Form
    {
        public TestForm()
        {
            Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            FormBorderStyle = FormBorderStyle.FixedSingle;
            Location = new Point(0, -uwfHeaderHeight); // Hide header.
            MaximizeBox = false;
            Size = new Size(Screen.PrimaryScreen.WorkingArea.Width, uwfHeaderHeight + 24); // + menu height.
            SizeGripStyle = SizeGripStyle.Hide;
            StartPosition = FormStartPosition.Manual;

            uwfMovable = false;
            
            var itemFile = new ToolStripMenuItem("File");
            var itemEdit = new ToolStripMenuItem("Edit");
            
            var itemFileOpen = new ToolStripMenuItem("Open");
            itemFileOpen.Click += (sender, args) =>
            {
                var ofd = new OpenFileDialog();
                var result = ofd.ShowDialog(); // Saving the result is pointless, it's not async stuff here.
                // What you can do is wait for form closing:
                ofd.FormClosed += (o, eventArgs) =>
                {
                    if (ofd.DialogResult == DialogResult.OK)
                    {
                        UnityEngine.Debug.Log(ofd.FileName);
                    }
                };
            };
            
            var itemFileExit = new ToolStripMenuItem("Exit");

            itemFile.DropDownItems.Add(itemFileOpen);
            itemFile.DropDownItems.Add(itemFileExit);
            
            var menu = new MenuStrip();
            menu.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            menu.AutoSize = false;
            menu.Location = new Point(0, uwfHeaderHeight); // Need to be placed below form's header.
            menu.Width = Width;
            menu.Items.Add(itemFile);
            menu.Items.Add(itemEdit);
            
            Controls.Add(menu);
        }

        protected override void OnPaint(PaintEventArgs e)
        { }

        protected override void OnPaintBackground(PaintEventArgs e)
        { }

        protected internal override void uwfOnLatePaint(PaintEventArgs e)
        { }
    }
```

> Or would you rather recommend just use native Unity GUI and create my own to simulate the Windows native GUI?

That's up to you.

**Comment by mariugul** [comment]
Thank you so much for the help! I attach my MonoBehaviour class to a gameObject to make it show but in your example you derive from Form class. How would you use this example on a gameObject to make it show up?

**Comment by Meragon** [comment]
Like this:
```csharp
public class GuiController : MonoBehaviour 
{
	private TestForm form;
	
    void Start()
	{
		form = new TestForm();
		form.Show();
	}
}
```

**Comment by mariugul** [comment]
Thank you so much, it worked great. I will pay it forward! :D
