### ISSUE TITLE
error CS0019: Operator '==' cannot be applied to operands of type 'DialogResult' and 'DialogResult'

### ISSUE THREAD

**Issue by mariugul** [Meragon/Unity-WinForms#37]
There is an error when importing the plugin to Unity when I compile the code, without altering it.

`Assets\StandaloneFileBrowser\StandaloneFileBrowserWindows.cs(39,29): error CS0019: Operator '==' cannot be applied to operands of type 'DialogResult' and 'DialogResult'
`

![image](https://user-images.githubusercontent.com/32439744/88483017-5d2b8080-cf65-11ea-8915-6f57afdabf3f.png)

**Comment by Meragon** [comment]
I can guess that you also imported original Windows Forms.

**Comment by Meragon** [comment]
Did you try to run example project from here https://github.com/Meragon/Unity-WinForms/releases/tag/11 ?

**Comment by mariugul** [comment]
It's working now, thanks!
