### ISSUE TITLE
Accessing Unity functionality from WinForms

### ISSUE THREAD

**Issue by mariugul** [Meragon/Unity-WinForms#38]
I'm trying to interact with game objects from the WinForms but can't seem to make it work. How would you go about turning on and off a game object from the WinForms class? What I hope to achieve is to make a WinForm button turn on and off a settings panel, which is a Unity game object. I'm running the script below to generate the tool strip. Since it doesn't derrive from `MonoBehaviour` I'm not able to directly attach and interact with game objects and was hoping it would be possible to just instanciate a class with the game object already connected. 

```sh
using UnityEngine;
using System.Drawing;
using System.Windows.Forms;

public class WinFormToolStrip : Form
{
    public WinFormToolStrip()
    {
        // Instances of Unity classes
        PanelOpener panelOpener = new PanelOpener();
        panelOpener.TogglePanel();
        ...
    }
```

**Comment by Meragon** [comment]
That's C# related question and there is multiple ways of achieving it. 
```csharp
public class TestForm : Form
{
	private PanelOpener panel;
	
	// 1. Dependency injection.
	public TestForm(PanelOpener panel) 
	{
		this.panel = panel;
	}
	
	// 2. Or just basic setter.
	public void SetPanel(PanelOpener panel)
	{
		this.panel = panel;
	}
	
	// 3. Singleton. Check down below.
	public TestForm()
	{
		panel = PanelOpener.instance;
	}
	
	// Other code...
}

public class PanelOpener : MonoBehaviour
{
	// 3. May be it's possible to use singleton?
	internal static PanelOpener instance;
		
	void Start()
	{
		if (instance != null)
			throw new InvalidOperationException("instance not null");
		
		instance = this;
	}
	
	// ------------------------------------------
	
	// Your method to toggle.
	public void TogglePanel() { }
}

public class GuiController : MonoBehaviour
{
	public PanelOpener panel; // Set in inspector.
		
	void Start()
	{			
		var form = new TestForm(panel);
		form.SetPanel(panel);
		form.Show();
	}
}
```

**Comment by mariugul** [comment]
Excuse my noobiness with the C# classes! The code works and I have my application pretty much up and running with your WinForms wrapper. I really appreciate you taking the time to help out. Thank you a lot.

**Comment by Meragon** [comment]
You welcome. And I appreciate for your contribute to this project, thank you.
