### ISSUE TITLE
Why is there no handle attribute

### ISSUE THREAD

**Issue by sui0312feng** [Meragon/Unity-WinForms#39]
Why is there no handle attribute

**Comment by sui0312feng** [comment]
"handle" of form or other control

**Comment by Meragon** [comment]
There was no need to use for me, so not implemented.

**Comment by sui0312feng** [comment]
ok!,can you  add "handle "  attribute ?

**Comment by Meragon** [comment]
No plans on that. Looking at the source, seems like not a 5 minute thing.
