### ISSUE TITLE
Just 2 small questions

### ISSUE THREAD

**Issue by Kenny7946** [Meragon/Unity-WinForms#42]
First of all, great Asset, love the look!

Altough i`ve got two small questions. 
First, the color of my TextBox is black when I focus it and regardless what i`m doing i can`t change it.. just want it to be the normal white color.
Second I couldn`t manage to change the FontStyle to Bold.

Would appreciate every help, thank you

**Comment by Kenny7946** [comment]
![Selected](https://user-images.githubusercontent.com/60717441/104163965-8480e780-53f7-11eb-848e-6e39990bae08.PNG)
![Unselected](https://user-images.githubusercontent.com/60717441/104163970-88146e80-53f7-11eb-8b8b-07d7fb94022c.PNG)

These are the Pictures for the TextBox, selected(top) and unselected(bottom). I dont want it to be black, searched all the source code but didnt find what I have to change so it doesnt change its color when selecting/unselecting. Can anyone help?

**Comment by Meragon** [comment]
The first issue was fixed in last commit 849957e0fcb5e035e7790bc38ee13a38abab6848 , maybe it's not working again in a new Unity version (I'm using 2019.3.9f1). I believe it also same issue as #33 
About fonts, what exactly you trying to do? To change font you gotta create a new one 
```
control.Font = new Font("Arial", FontStyles.Bold);
```
Or check font itself, maybe bold style is not supported.

**Comment by Kenny7946** [comment]
Hi Meragon, thank you for your answer.

I downloaded an earlier version (the one you mentioned) and unfortunately it didnt work, but then i build the game and there the bug is gone, so everything is fine. 

Yep,  bold style is not supported but that doesnt hurt either, managed a workaround.
