### ISSUE TITLE
Multiselect for OpenFileDialog or ListBox

### ISSUE THREAD

**Issue by damonftl** [Meragon/Unity-WinForms#43]
Hi, I can't seem to get any multiselect functionality with any of the form elements. You can't use the multiselect parameter with the open file dialogs, and with a ListBox there seems to be no way to set it so you can select multiple items. I'm kind of at a loss. I need a way to select multiple things, whether it's more than one file in an OpenFileDialog or just being able to pick more than one thing in a ListBox, either would be great. 

Maybe I'm missing something? Are checkboxes the only way to have more than one selection in the same group of things?

**Comment by Meragon** [comment]
Hey.
Yeah, the closest thing you can do for ListBox or TreeView is override painting methods and mark selected elements/items by yourself.
As for file dialog box, you will need to change source code.

**Comment by damonftl** [comment]
Thanks for the reply, it's good to know at least that it wasn't just me missing something. I ended up going with checkboxes for now, but I'll definitely have to do something like the ListBox override eventually.
