### ISSUE TITLE
Creating Custom Events

### ISSUE THREAD

**Issue by Kenny7946** [Meragon/Unity-WinForms#44]
I am using the PanelMenuStrip from your Example, but I would like to have some more Events for the ToolStripMenuItems (like MouseEnter/ MouseLeave). Can you give me some tips on implementing this?

**Comment by Meragon** [comment]
Sounds like you want to add complicated events. Toolstrip items are being controlled in the ToolStrip class (painting/mouse hovering and etc), so you probably gotta look there and override it's methods or change the source class. There is many issues with that implementation, I was considering to rewrite it, but now yeah, this project at the questionable state, no plans on that.

**Comment by Kenny7946** [comment]
Okay, I am gonna have a look at it, thanks for your reply.
