### ISSUE TITLE
Can't disable resizing

### ISSUE THREAD

**Issue by NotBjoggisAtAll** [Meragon/Unity-WinForms#45]
I can't figure out how to disable resizing of a form.

I have tried to change the ControlResizeTypes type by calling SetResize(ControlResizeTypes.None).

The only solution I have figured out now is to set the min/max size to the same values, but this still allows the user to hover an edge to get the resize cursor.

**Comment by Meragon** [comment]
```
form.FormBorderStyle = FormBorderStyle.FixedSingle;
```

**Comment by NotBjoggisAtAll** [comment]
Thanks, is it also possible to stop the panel from being moved? Sorry for asking all this here, idk if it is a documentation page I can look at

**Comment by Meragon** [comment]
If you asking about form and not panel then there is field uwfMovable, also you can override OnMouseDown
```
protected override void OnMouseDown(MouseEventArgs e)
{ }
```
I believe it should disable resizing and moving. As for documentation, the project is based on Microsoft's WindowsForms and it's documentation can be found [here](https://docs.microsoft.com/en-us/dotnet/desktop/winforms/?view=netframeworkdesktop-4.8).

**Comment by NotBjoggisAtAll** [comment]
Thanks!
