### ISSUE TITLE
How to use it in Unity

### ISSUE THREAD

**Issue by PaulinePr** [Meragon/Unity-WinForms#47]
Hi,
I'm sorry to bother you, I'm a student and I have to code an application using Unity and Windows Form but I don't know how to code with that. 
Is there an easy way to put what you did in a unity project ? Or should I write it all other again to make it work ? 
Thank you very much for your answer.

**Comment by Meragon** [comment]
Hey, check the releases https://github.com/Meragon/Unity-WinForms/releases/tag/11
There is example project.
