### ISSUE TITLE
No Example 

### ISSUE THREAD

**Issue by aammfe** [Meragon/Unity-WinForms#6]
Thanx for this Great Effort ,But problem is i dont know where to start ?
means there is no Example scene , no guide.

**Comment by Meragon** [comment]
Check releases, there is an example project. It's a little bit outdated.
Just copy and rewrite scripts with newest ones.

**Comment by aammfe** [comment]
Thanx for Quick Response ,

 so what you have future planes for this? r you going to make full replica of MS Window Form?

**Comment by Meragon** [comment]
> so what you have future planes for this? r you going to make full replica of MS Window Form?
and one more this 

I'm not sure about this. There is a lot of stuff to do. Right now I'm doing something like a DataGridView, but more simplified and also I should complete scrollbox controls.
The deal is that I'm not going to leave this project, cause it's part of another one.

> list box has visualized list?

I don't know what are you talking about. 
In any case it's better to use TreeView at the moment. It has more features and way faster rendering. Also you can override DrawNode method if needed.

**Comment by aammfe** [comment]
List Virtualization Means

list.DataSource.count // 100000

means list have to create 100000 items in scrollBox ?
nope you will create just visible items , and when item goes off screen , reassign data and reposition to End .

means no need to create and scroll items 10000 unnecessary Items ,  

[Listview Virtualization](https://blogs.msdn.microsoft.com/alainza/2014/09/03/listview-basics-and-virtualization-concepts/)

you will know this concept by other name.

**Comment by Meragon** [comment]
I see. It's not implemented yet.

**Comment by aammfe** [comment]
So what is you ultimate goal.
i m asking you because i have spend lot of time on unity UIs , NGUI , UGUI , 
but only Listview kept me behind.

**Comment by Meragon** [comment]
I'm not planning of making a replica of WinForms. This project already have a nice base to implement your own controls. As far as I needed new controls, I'll implement them then. 
This project is directly related to another project (from my current job), and for me it makes no sense to leave it.

**Comment by aammfe** [comment]
ok ill keep my finger crossed for a list control.
with virutalization.

**Comment by Meragon** [comment]
Maybe in next year. We'll soon release alpha version of related project, I think at the end of this year. And there is a lot of stuff I need to finish.
