### ISSUE TITLE
MenuStrip renders over titlebar

### ISSUE THREAD

**Issue by Dummiesman** [Meragon/Unity-WinForms#8]
Neat project. Only issue I've encountered so far.

**Comment by Meragon** [comment]
If you mean form titlebar, then you can override OnLatePaint method and render your own one. Right now it's rendering in normal OnPaint method, and after that form rendering every control it has. In a good way forms should override ClientRectangle property and prohibit rendering everything outside the rect. And it also should affect scrollbars (in the near future may be).
Let me know if you mean something else.

**Comment by Dummiesman** [comment]
Hm actually it seems all controls wind up covering the title bar. Why does that happen? I copied some control code from a winforms project I made in VS.

**Comment by Meragon** [comment]
Because you need to adjust their location. 
```
myButton.Location = new Point(myButton.Location.X, myButton.Location.Y + 24); // Default HeaderHeight value.
```
Form is not doing it by it self at the moment. There is some cons and pros to not implement it.
