### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AdamFrisby** [Meragon/Unity-WinForms#9]
Hi there,

This project looks incredibly useful for use in larger projects - unfortunately the GPL means it's basically impossible to use in a commercial context. Could you consider a re-license to Apache2/MIT/BSD or LGPL?

Thanks!

**Comment by Meragon** [comment]
Hey.
Yeah, it's fine, I'll change it to MIT.

**Comment by AdamFrisby** [comment]
Awesome, thanks!

**Comment by Meragon** [comment]
You welcome.
